### ISSUE TITLE
[Question] totp getenv() 

### ISSUE THREAD

**Issue by raykman** [ian-young/API_Scripts#28]
Line 211 of delete_device.py.

# Prepare login data
    login_data = {
        "email": username,
        "password": password,
        "otp": generate_totp(getenv("totp_secret")),
        "org_id": org_id,
    }

Why do we not pass the totp as a variable like the rest? Is this a security feature?

**Comment by ian-young** [comment]
Correct, it is because you would need to include the TOTP secret in plaintext. If you are running it on your local machine and not sharing the script, you're good to have it in plain text but I'd advise against it just to prevent accidentally leaking the secret. The secret is essentially the seed that the algorithm uses for the rotation of the six-digit code.
